kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: benzoh/myapp:test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  volumes:
    - name: mysql-pv-storage
      persistentVolumeClaim:
       claimName: mysql-pv-claim
  containers:
    - image: benzoh/mydb:test
      name: mysql
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-pv-storage
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpmyadmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mysql-service
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: myapp
    protocol: TCP
    port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  clusterIP: None
  # type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
## serviceにselectorを設定しない場合独自にエンドポイントを設定する
# kind: Endpoints
# apiVersion: v1
# metadata:
#   name: myapp
# subsets:
#   - addresses:
#       - ip: 1.2.3.4
#     ports:
#       - port: 9376
