kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: benzoh/myapp:test
        ports:
        - containerPort: 80
      - name: mydb
        image: benzoh/mydb:test
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - name: data
          # mountPath: /db
          mountPath: /db-data
      volumes:
      - name: data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - name: myapp
    protocol: TCP
    port: 80
    targetPort: 80
  - name: mydb
    protocol: TCP
    port: 3306