apiVersion: v1
kind: Service
metadata:
  name: minikubetestapp
spec:
  type: NodePort
  selector:
    app: minikubetestapp
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP